language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22
    - android-16
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:  sh update_android.sh && ./gradlew build

# whitelist
branches:
  only:
    - gradle_build
